#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/Users/alekspo/SDKs/gwt-2.7.0/gwt-user.jar:/Users/alekspo/SDKs/gwt-2.7.0/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src main.java.online.draughts.rus.shared.locale.DraughtsMessages -createMessages ;

