package online.shashki.rus.client.resources.images;

import com.google.gwt.resources.client.ClientBundle;
import com.google.gwt.resources.client.ImageResource;

/**
 * Auto Generated by mk_images.rb on Fri Nov 30 22:39:12 -0500 2012
 */
public interface Images extends ClientBundle {
  @Source("img/online.png")
  ImageResource onlineIconImage();

  @Source("img/offline.png")
  ImageResource offlineIconImage();

  @Source("img/playing.png")
  ImageResource playingIconImage();

  @Source("img/busy.gif")
  ImageResource busyIconImage();

  @Source("img/loading.gif")
  ImageResource loadIconImage();

  @Source("img/black-win.png")
  ImageResource blackWin();

  @Source("img/white-win.png")
  ImageResource whiteWin();
}
